codecov:
  require_ci_to_pass: yes
  token: 407c3882-4838-44b2-8558-20dc8a7f6e2b

coverage:
  precision: 2
  round: down
  range: 60..85
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,files,footer"
  behavior: default
  require_changes: no
