# author: cboveda

name: Build
on:
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Project Builder
    runs-on: ubuntu-latest
    steps:
      # Checks out the active branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      # Access the private repo
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Cache library files to improve build time
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-psyche-game-WebGL
          restore-keys: |
            Library-psyche-game
            Library-
      
      # Builder
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-13
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          sshAgent: ${{ env.SSH_AUTH_SOCK }}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      # Checks out the active branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache library files to improve build time
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-psyche-game-WebGL
          restore-keys: |
            Library-psyche-game
            Library-

      # Test Runner
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.3.18f1
          testMode: All
          customParameters: |
            -debugCodeOptimization 
            -enableCodeCoverage 
            -coverageResultsPath ./coverage-results 
            -coverageOptions generateAdditionalMetrics

      # CodeCov integration
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: automated
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-results/**/*.xml






